# Generated by Django 5.1 on 2024-08-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('profession', models.CharField(max_length=1000)),
                ('comment', models.CharField(max_length=2500)),
                ('avatar', models.ImageField(upload_to='img/%y')),
                ('youtube', models.CharField(max_length=2500)),
            ],
        ),
    ]
