# Generated by Django 5.1 on 2024-08-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoScrollSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=1000)),
                ('logo', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
