# Generated by Django 5.1 on 2024-08-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0002_logoscrollsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=3000)),
            ],
        ),
    ]
