# Generated by Django 5.1 on 2024-09-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0004_coursedetailssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetailsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('popup_link', models.CharField(max_length=1000)),
                ('button_link', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='img/%y')),
                ('heading', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('second_heading', models.CharField(blank=True, max_length=1000, null=True)),
                ('list_01', models.CharField(blank=True, max_length=1000, null=True)),
                ('list_01_desc', models.CharField(blank=True, max_length=2500, null=True)),
                ('list_02', models.CharField(blank=True, max_length=1000, null=True)),
                ('list_02_desc', models.CharField(blank=True, max_length=2500, null=True)),
                ('list_03', models.CharField(blank=True, max_length=1000, null=True)),
                ('list_03_desc', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
    ]
